### ISSUE TITLE
Colors and numbers in the sunburst 

### ISSUE THREAD

**Issue by aostropolets** [mi-erasmusmc/TreatmentPatterns#2]
Rather a question than an issue: it seems that you use Sunburst 2.0 package for your sunburst. I encountered two really annoying issues: 1. It won’t output percentages on the plot, only in the interactive version and b) it’s super hard to maintain same color scale across subgroup analysis/disjoint sunbursts even with leveling and ordering. I’m wondering you’ve been a thinking about that or maybe used something else for you papers on pathways.

**Comment by AniekMarkus** [comment]
Sorry for the late response, I missed your message earlier. 1. I have not looked into this. 2. Fixing colors is not yet supported by the package, but it is possible to hard code it in the html file for the sunburst plot by defining var colors = {"name event cohort": "#FFFFFF", ...} instead of using options.colors = d3.scaleOrdinal(d3.schemeCategory20.concat(d3.schemeCategory20)).
